variables:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  UPX_URL: https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
  GO_METALINTER_URL: https://github.com/alecthomas/gometalinter/releases/download/v3.0.0/gometalinter-3.0.0-linux-amd64.tar.gz
  DEBIAN_FRONTEND: noninteractive

stages:
  - test
  - build
  - release
  - deploy

cleancode:
  image: golang:1.20-buster
  stage: test
  coverage: /^Grade:\s*[A-Z]\+?\s*\((\d+.\d+)\%\)/
  variables:
    FAIL_ON_CONTROLLER: "1"
  script:
    - |
      if [ ! -f "$GOPATH/bin/goreportcard-cli" ]; then \
      go install github.com/gordonklaus/ineffassign@latest && \
      go install github.com/client9/misspell/cmd/misspell@latest && \
      go install github.com/fzipp/gocyclo/cmd/gocyclo@latest && \
      go install golang.org/x/lint/golint@latest && \
      go install github.com/gojp/goreportcard/cmd/goreportcard-cli@latest && \
      curl -sSL "$GO_METALINTER_URL" -o gometalinter.tar.gz && \
      tar -xzvpf gometalinter.tar.gz --strip-components=1 -C "$GOPATH/bin" && \
      rm gometalinter.tar.gz ; \
      fi
    - goreportcard-cli -v 2>/dev/null
    - |
      if [ "$FAIL_ON_CONTROLLER" = "1" ]; then \
      go test -timeout 30s -v -tags sqlite -run ^TestController$ api/app/controller ; \
      fi
  only:
    changes:
      - app/*
      - app/**/*
      - docs/*
      - .gitlab-ci.yml
      - kubernetes-deployment.yml
      - Dockerfile
      - "*.go"
      - go.*

docs:
  image: golang:1.20-buster
  stage: test
  coverage: /^total:[^\d]+(\d+.\d+)\%/
  script:
    - |
      if [ ! -f "$GOPATH/bin/swag" ]; then \
      go install github.com/swaggo/swag/cmd/swag@latest; \
      fi
    - swag init
  only:
    changes:
      - app/*
      - app/**/*
      - docs/*
      - .gitlab-ci.yml
      - kubernetes-deployment.yml
      - Dockerfile
      - "*.go"
      - go.*

unit-testing:
  image: golang:1.20-buster
  stage: test
  coverage: /^total:[^\d]+(\d+.\d+)\%/
  script:
    - echo "Validating routes..."
    - touch router-logs.txt
    - |
      find app/controller/ \
      -maxdepth 1 \
      -mindepth 1 \
      -type d \
      -exec sh -c 'cat app/routes/router.go | grep "api/{}" || echo "{}: controller defined but router not registered" >> router-logs.txt' \;
    - if [ "`cat router-logs.txt | wc -w`" != "0" ]; then cat router-logs.txt && exit 2; fi
    - CGO_ENABLED=1 go test -v -coverprofile cover.txt ./...
    - go tool cover -func cover.txt
  only:
    changes:
      - app/*
      - app/**/*
      - docs/*
      - .gitlab-ci.yml
      - kubernetes-deployment.yml
      - Dockerfile
      - "*.go"
      - go.*

build:
  image: golang:1.20-buster
  stage: build
  script:
    - |
      if [ ! -f "$GOPATH/bin/upx" ]; then \
      apt update && apt install -y --no-install-recommends xz-utils && \
      go get -v github.com/pwaller/goupx && \
      curl -ksSL $UPX_URL -o /tmp/upx.tar.xz && \
      mkdir -p $GOPATH/src/upx && \
      tar -xJvpf /tmp/upx.tar.xz --strip-components=1 -C $GOPATH/src/upx && \
      ln -s $GOPATH/src/upx/upx $GOPATH/bin/upx; \
      fi
    - rm -rf docs/*.go
    - sed -i "s/v1.0.0/v1.0.0-$(date +%Y%m%d%H%M%S)/" app/controller/api_info_get.go
    - go get -d -v
    - GO111MODULE=on go build -a -tags "netgo production" -ldflags '-s -w -extldflags "-static"' -o app.run .
    - goupx app.run
    - if [ -f /etc/ssl/certs/ca-certificates.crt ] ; then cp /etc/ssl/certs/ca-certificates.crt . ; fi
    - if [ -f /etc/nsswitch.conf ] ; then cp /etc/nsswitch.conf . ; fi
  artifacts:
    expire_in: 15 minutes
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - app.run
      - ca-certificates.crt
      - nsswitch.conf
  only:
    refs:
      - master
      - staging
    changes:
      - app/*
      - app/**/*
      - docs/*
      - .gitlab-ci.yml
      - kubernetes-deployment.yml
      - Dockerfile
      - "*.go"
      - go.*
  needs: ["cleancode", "docs", "unit-testing"]
  when: on_success

release:
  stage: "release"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
  needs: ["build"]
  only:
    refs:
      - master
      - staging
    changes:
      - app/*
      - app/**/*
      - docs/*
      - .gitlab-ci.yml
      - kubernetes-deployment.yml
      - Dockerfile
      - "*.go"
      - go.*
  when: on_success

deploy_staging:
  stage: "deploy"
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  environment:
    name: staging
    url: https://kasirdev.monstercode.net
  script:
    - sed -i "s/{APP_VERSION}/v$(date +%Y\.%-m\.%-d-%-H%M%S)/g" kubernetes-deployment.yml
    - sed -i "s/{ENV_NAME}/stg/g" kubernetes-deployment.yml
    - sed -i "s/{REPLICAS}/${REPLICAS:-2}/g" kubernetes-deployment.yml
    - kubectl --kubeconfig="$K8S_DO_SECRET_STG" apply -f kubernetes-deployment.yml
  needs: ["release"]
  only:
    refs:
      - master
      - staging
    changes:
      - app/*
      - app/**/*
      - docs/*
      - .gitlab-ci.yml
      - kubernetes-deployment.yml
      - docs/*
      - Dockerfile
      - "*.go"
      - go.*
  when: on_success

# deploy:production:
#   stage: "deploy"
#   image: morkid/ssh-client
#   needs: ["release"]
#   script:
#     - cat "$PRODUCTION_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
#     - ssh -p $PRODUCTION_PORT $PRODUCTION_USER@$PRODUCTION_SERVER "mkdir -p $PRODUCTION_DIR"
#     - |
#       ssh -p $PRODUCTION_PORT \
#       $PRODUCTION_USER@$PRODUCTION_SERVER \
#       "cd $PRODUCTION_DIR && docker-compose pull ms-master && docker-compose up -d --force-recreate ms-master && docker-compose up -d --force-recreate nginx"
#   only:
#     refs:
#       - master
#   when: manual