apiVersion: v1
kind: Service
metadata:
  name: transaction-service-cluster
  namespace: kasir-kita
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: transaction-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: kasir-kita
  labels:
    app: transaction-service
spec:
  selector:
    matchLabels:
      app: transaction-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  replicas: {REPLICAS}
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      hostPID: true
      containers:
        - image: registry.tog.co.id/monstergroup-solo/kasirkita/transaction-service:latest
          name: transaction-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "{APP_VERSION}"
            - name: APP_NAME
              value: "transaction-service"
            - name: ENDPOINT
              value: "/api/v1/transaction"
            - name: APP_ID
              value: "6A6EF734-F557-4F7E-9C2A-32CD28E43420"
            - name: APP_DESCRIPTION
              value: ""
            - name: PORT
              value: "8000"
          envFrom:
            - secretRef:
                name: global-config
          startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 0
            failureThreshold: 30
            periodSeconds: 3
      imagePullSecrets:
        - name: regcred